### ISSUE TITLE
Swift/Sample Project

### ISSUE THREAD

**Issue by ttrushin** [piemonte/PBJHexagon#4]
Hi,
Could you possibly provide a sample project showing how to use this in Swift 2.0?  I'd like to use your layout and be able to load content into the cells.

Thanks!

**Comment by piemonte** [comment]
thanks much, i'll give this project some help when i can

**Comment by vatsal1992** [comment]
Hi,
You made an amazing custom collectionview layout.
i request you to attach sample project.
i'm trying to implement for horizontal scrolling.
